run:
  # if you are daring, set this to true
  tests: false

linters:
  enable:
    - gofmt
    - bodyclose
    - exhaustive
    - dupl
    - errorlint
    - prealloc
    - importas
    - errorlint
    - errname
    - revive
    - gocritic
    - staticcheck
    - gosimple
    - govet
    - ineffassign
    - typecheck
    - unused
    - misspell
    - goimports
    - tenv
    # - gochecknoglobals
    - gochecknoinits
    # - gci
    - usestdlibvars
    - thelper
    - nolintlint
    - noctx
    - wrapcheck
    - gocognit
    # - containedctx
    # - contextcheck
    - godot
    - nosprintfhostport
  # disable:
  #   - goanalysis_metalinter

linters-settings:
  # importas:
    # if set to `true`, force to use alias.
    # no-unaliased: true
    # List of aliases
    # alias:
    #   - pkg: github.com/opencontainers/go-digest
    #     alias: digest
  
  exhaustive:
    default-signifies-exhaustive: true

  staticcheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.19"
    # https://staticcheck.io/docs/options#checks
    checks: [ "all" ]

  revive:
    ignore-generated-header: true
    severity: warning
    # enable-all-rules: true
    # rules:
    # - name: banned-characters
    #   arguments: [""]
    # - name: line-length-limit
    #   severity: warning
    #   arguments: [200]
    # - name: function-result-limit
    #   arguments: [4]
    rules:
      - name: atomic
      # - name: line-length-limit
      #   severity: warning
      #   arguments: [120]
      - name: unhandled-error
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      # - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: defer
      - name: useless-break
      - name: unexported-naming
      # - name: cognitive-complexity
      #   arguments: [35]
      - name: use-any
      - name: deep-exit
      # - name: add-constant
      - name: unnecessary-stmt
      - name: modifies-value-receiver
      # - name: constant-logical-expr
      - name: call-to-gc
      - name: import-shadowing
      # - name: unused-receiver


  goimports:
    # Put imports beginning with prefix after 3rd-party packages.
    # It's a comma-separated list of prefixes.
    # Default: ""
    local-prefixes: git.act3-ace.com/ace

  wrapcheck:
    ignoreSigs:
      # defaults
      - ".Errorf("
      - ".Err("
      - "errors.New("
      - "errors.Unwrap("
      - ".Wrap("
      - ".Wrapf("
      - ".WithMessage("
      - ".WithMessagef("
      - ".WithStack("
    ignoreSigRegexps:
      # ignore printing (to stdout)
      - "fmt\\..?(P|p)rint.*\\(" 
      - "\\(git.act3-ace.com/ace/data/tool/pkg/.*"

  gocognit:
    min-complexity: 35

issues:
  # uncomment to enable more linting
  # exclude-use-default: false

  include:
    - EXC0005
    # - EXC0012
    # - EXC0009
    # - EXC0002
